In [6]:
# 序列填充post

import tensorflow as tf     #导入所需库
s=[[1],[2,3],[4,5,6]]       #初始化填充前序列s
print("填充前序列为\n",s)  #显示填充前序列
a=tf.keras.preprocessing.sequence. pad_sequences(s, padding='post')
print("填充后序列为\n",a)  #显示填充后序列

填充前序列为
 [[1], [2, 3], [4, 5, 6]]
填充后序列为
 [[1 0 0]
 [2 3 0]
 [4 5 6]]


In [7]:
# 序列裁剪pre

import tensorflow as tf        #导入所需库
s=[[1,2,3,9],[4,5,6],[7,8]]    #初始化裁剪前序列s
print("剪裁前序列为\n",s)     #显示剪裁前序列
a=tf.keras.preprocessing.sequence. pad_sequences(s,maxlen=2)
print("剪裁后序列为\n",a)     #显示剪裁后序列

剪裁前序列为
 [[1, 2, 3, 9], [4, 5, 6], [7, 8]]
剪裁后序列为
 [[3 9]
 [5 6]
 [7 8]]


In [20]:
# 构建含嵌入层的Keras网络模型

import tensorflow as tf      #导入所需库
import numpy as np
model=tf.keras.Sequential()  #构建空的网络模型model
#创建嵌入层并添加到model中
embedding=tf.keras.layers.Embedding(output_dim=32, input_dim=100, input_length=400)
model.add(embedding)         #将嵌入层添加到model中
model.build(input_shape=(None, 400))
model.summary()              #显示深度学习网络的参数信息
#显示embeddings矩阵
e=np.array(embedding.get_weights())
print("embeddings矩阵的值\n",e)
#定义句子数据集
text="Deep learning is an important concept raised by the current sciences."
#分词
token=tf.keras.preprocessing.text.Tokenizer(num_words=100)
token.fit_on_texts(text)     #分词语句
#将词转换为整数序列
input=token.texts_to_sequences(text)
#对序列进行填充处理
input_array=tf.keras.preprocessing.sequence.pad_sequences(input,
           maxlen=400, truncating='post')
#使用模型获取转换后向量
output_array=model.predict(input_array)
print("输出矩阵的形状",output_array.shape)

Model: "sequential_18"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_18 (Embedding)             │ (None, 400, 32)             │           3,200 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,200 (12.50 KB)

 Trainable params: 3,200 (12.50 KB)

 Non-trainable params: 0 (0.00 B)

embeddings矩阵的值
 [[[ 0.02721757 -0.02693101  0.01621744 ... -0.01052541  0.00483906
   -0.04285712]
  [ 0.03759662 -0.0126259  -0.03502363 ...  0.01408863 -0.04716123
    0.00689114]
  [ 0.0158785  -0.02443242 -0.00775502 ...  0.03963147  0.02771086
    0.04988981]
  ...
  [ 0.02386283 -0.03644081  0.03488714 ...  0.03700235 -0.00915053
    0.00602891]
  [-0.04039443  0.01030465 -0.00259615 ...  0.04702959  0.04949646
    0.02693888]
  [-0.03129169 -0.04932899  0.04073583 ...  0.03648328  0.03096652
   -0.0450501 ]]]
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step
输出矩阵的形状 (69, 400, 32)


In [23]:
import tensorflow as tf      #导入所需库

# 构建RNN模型
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(10, 5, input_length=6))  # 嵌入层
model.add(tf.keras.layers.SimpleRNN(128))                    # 简单循环层
model.add(tf.keras.layers.Dense(5, activation='softmax'))    # 输出层
model.build(input_shape=(None,6))
model.summary()  # 显示网络模型参数信息


Model: "sequential_20"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_20 (Embedding)             │ (None, 6, 5)                │              50 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn_12 (SimpleRNN)            │ (None, 128)                 │          17,152 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 5)                   │             645 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 17,847 (69.71 KB)

 Trainable params: 17,847 (69.71 KB)

 Non-trainable params: 0 (0.00 B)